# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TEST": "00_core.ipynb",
         "test": "01_matmul.ipynb",
         "test_eq": "01_matmul.ipynb",
         "near": "01_matmul.ipynb",
         "test_near": "01_matmul.ipynb",
         "get_data": "02_fully_connected.ipynb",
         "normalize": "02_fully_connected.ipynb",
         "test_near_zero": "02_fully_connected.ipynb",
         "mse": "02_fully_connected.ipynb"}

modules = ["core.py",
           "matmul.py",
           "fully_connected.py"]

doc_url = "https://fastai.github.io/myfastai/"

git_url = "https://github.com/fastai/myfastai/tree/master/"

def custom_doc_links(name): return None
