# AUTOGENERATED! DO NOT EDIT! File to edit: 02_fully_connected.ipynb (unless otherwise specified).

__all__ = ['get_data', 'normalize', 'test_near_zero', 'mse']

# Cell
from .matmul import *
from pathlib import Path
from IPython.core.debugger import set_trace
#from fastai import datasets
import pickle, gzip, math, torch, matplotlib as mpl
import matplotlib.pyplot as plt
from torch import tensor

def get_data(path = "/home/petr/data/mnist.pkl.gz"):
    with gzip.open(path, 'rb') as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding='latin-1')
    return map(tensor, (x_train,y_train,x_valid,y_valid))

def normalize(x, m, s): return (x-m)/s

# Cell
def test_near_zero(a,tol=1e-3): assert a.abs()<tol, f"Near zero: {a}"

# Cell
from torch.nn import init

# Cell
def mse(output, targ): return (output.squeeze(-1) - targ).pow(2).mean()

# Cell
from torch import nn