# AUTOGENERATED! DO NOT EDIT! File to edit: 01_matmul.ipynb (unless otherwise specified).

__all__ = ['test', 'test_eq', 'near', 'test_near']

# Cell
from .core import *
import operator

def test(a, b, cmp, cname=None):
    if cname is None: cname = cmp.__name__
    assert cmp(a, b), f"{cname}: \n{a}\n{b}"

def test_eq(a, b):
    test(a, b, operator.eq, "==")

# Cell
import torch

def near(a,b): return torch.allclose(a, b, rtol=1e-3, atol=1e-5)
def test_near(a,b): test(a,b,near)